name: GitHub Release

on:
  push:
    tags:
      - "*-v*" # Updated to catch tags like 'WNprolog-3.1-v1.0.0'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
          draft: false
          make_latest: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
